- labscript_devices/__init__.py
- labscript_devices/__version__.py
- setup.cfg
Per labscript-suite/runmanager#81, with the addition of making the importlib_metadata requirement python<'3.8'.
> Obtain own version without external functions

- labscript_devices/SpinnakerCamera/__init__.py
- labscript_devices/SpinnakerCamera/blacs_tabs.py
- labscript_devices/SpinnakerCamera/blacs_workers.py
- labscript_devices/SpinnakerCamera/labscript_devices.py
- labscript_devices/SpinnakerCamera/register_classes.py
This pull request contains a new camera interface that uses FLIR's PySpin/Spinnaker API. SpinnakerCamera is intended for users of FlyCapture2Camera that want to run labscript with Python 3.6 and newer. SpinnakerCamera requires PySpin and the Spinnaker SDK. The new code was written by S. Eckel.
We've successfully tested SpinnakerCamera in our lab using Flea3 13Y3M. During testing/coding, we've noticed that PySpin has some bugs related to when/if certain camera parameters can be set (this problem also occurs in FlyCapture2). Presumably, the parameter programming order does not depend on camera model, but we cannot be sure. Other users should be aware of the general shoddiness of FLIR's python code when deploying on their apparatus.
DSB
> SpinnakerCamera

- labscript_devices/DummyPseudoclock/labscript_devices.py
- labscript_devices/DummyPseudoclock/register_classes.py
- labscript_devices/DummyPseudoclock/runviewer_parsers.py
This PR permits whole-suite works-out-of-the-box changes by adding a runviewer parser to DummyPseudoclock (resolves #52).
The additions to the `generate_code` method of `DummyPseudoclock` and the `get_traces` method of `DummyPseudoclockParser` mock `labscript_devices.PineBlaster`, which appeared to be the simplest non-dummy pseudoclock device to mimic the instruction set and runviewer parser of.
> Save clock instructions and add runviewer parser for DummyPseudoclock

- .github/workflows/release.yml
- labscript_devices/__version__.py
- pyproject.toml
- setup.py
This fixes the circular dependency issue between blacs and labscript-devices that is preventing #70 from building. By extension, allows for proper pip develop installs locally, where this circular dependency issue is manifesting.
Pretty sure I got all the tweaks from labscript-utils, but best to make sure I didn't miss anything, especially where the workflows/RTD stuff is concerned since that is harder to test locally.
This should be merged at the same time as labscript-suite/blacs#82
> Update default setuptools_scm version scheme to release-branch-semver.

- labscript_devices/PrawnBlaster/__init__.py
- labscript_devices/PrawnBlaster/blacs_tabs.py
- labscript_devices/PrawnBlaster/blacs_workers.py
- labscript_devices/PrawnBlaster/labscript_devices.py
- labscript_devices/PrawnBlaster/register_classes.py
- labscript_devices/PrawnBlaster/runviewer_parsers.py
This PR provides support for the new PrawnBlaster pseudoclock (firmware release in [labscript-suite/PrawnBlaster](https://github.com/labscript-suite/PrawnBlaster))
PrawnBlaster Specs:
* Configurable as 1, 2, 3, or 4 truly independent pseudoclocks. Each pseudoclock has it's own independent instruction set - there need be no synchronisation between pseudoclock instructions. It is equivalent to having up to 4 PineBlaster boards on a single chip!
* 30,000 instructions (each with up to 2^32 repetitions) if configured as a single pseudoclock. Instructions are spread evenly amongst pseudoclocks if configured between 2 and 4 pseudoclocks (15,000, 10,000, and 7,500 respectively).
* Minimum pulse half-period 50ns (if internal clock running at 100MHz).
* Maximum pulse half-period ~42.9 seconds (if …
> Support for the PrawnBlaster pseudoclock

- labscript_devices/TekScope/blacs_workers.py
Resolves #64 using proposal of @ispielma.
> Tekscope bugfix

- docs/source/adding_devices.rst
- docs/source/conf.py
- docs/source/devices/ni_daqs.rst
- docs/source/introduction.rst
- labscript_devices/LightCrafterDMD.py
This fixes #81. It also helps the PDF docs with overrun lines by having the pages be landscape, and it fixes a number of broken intersphinx cross-references.
> Fix for PDF docs build

- labscript_devices/PrawnBlaster/runviewer_parsers.py
There was a bug where runviewer did not correctly parse pulse programs for pseudoclocks/clocklines 1, 2, and 3. There were several bugs (redefinition of a global variable inside a loop and a loop nested when it shouldn't have been.
This should now be resolved. Thanks to Amilson Fritsch for discovering this.
> Fixed PrawnBlaster runviewer class

- docs/source/adding_devices.rst
- docs/source/devices.rst
- docs/source/devices/andorsolis.rst
- docs/source/devices/flycapture2.rst
- docs/source/devices/ni_daqs.rst
- docs/source/devices/opalkellyXEM3001.rst
- docs/source/devices/prawnblaster.rst
- docs/source/devices/pulseblaster.rst
- docs/source/devices/pulseblaster_no_dds.rst
- docs/source/devices/pylon.rst
- docs/source/devices/spinnaker.rst
- docs/source/introduction.rst
- docs/source/user_devices.rst
Adds a small section to the docs for listing 3rd party devices repos.
@zakv Nothing really fancy here unless you can think of something to spruce it up. Could use your thoughts on how to actually put the links in (ie just have bare URLs, some sort of text, etc).
> 3rd Party Repo List

- labscript_devices/FunctionRunner/labscript_devices.py
Instead of remaining in the order they were added. Functions are
intended to be sorted by time, but not by anything else. But naively
sorting the tuples caused them to be sorted unintentionally by name if
they had the same time.
> Fix bug where FunctionRunner functions were sorted by name

- labscript_devices/FunctionRunner/utils.py
In h5py 3.0, all strings from datasets are returned as bytestrings:
https://github.com/h5py/h5py/issues/1338
Luckily this isn't more of an issue throughout the labscript suite,
because we still have lots of code that is unassuming about string
datatypes due to the port from Python 2. But it will probably show up
elsewhere too.
> Fix bug in FunctionRunner function deserialisation

- labscript_devices/PulseBlaster_No_DDS.py
This PR "fixes" labscript-suite/labscript-devices#23.
Basically, some older PB firmware will blank all outputs when in programming mode. The current code always enters programming mode to be compatible with the 'pb_stop_programming/STOP' scheme.
This tweak shuffles things around so pb_start_programming() is only called if necessary: either for programming or for the 'pb_stop_programming/STOP' scheme. Combined with the 'pb_start/BRANCH' scheme, the outputs will not blank between shots if there are no updates to the programming when using the old firmware. 
We have tested this on PBs with and without this issue for a long time without problems, though we don't use the 'pb_stop_programming/STOP' scheme. This helps the experiment to generally stay warm without changing any real functionality …
> Pulseblaster transition_to_buffered tweak

- labscript_devices/NI_DAQmx/labscript_devices.py
Just tried the changes in #75 on a DAQ without analog inputs and found a fairly important edge case in the logic. Basically, the changes I made assume analog inputs exist.
This PR adds a bit of logic to handle the case when the DAQ has no analog inputs.
> Fix recent AI termination changes to work with DAQs that don't have analog inputs

- labscript_devices/IMAQdxCamera/blacs_tabs.py
The former doesn't exist in PyQt5 or PySide2, causing BLACS to fail to load `ImaqdxCamera` tabs.
I do see google results for `QtGui.QSizePolicy`, so it existed at some point - perhaps in Qt4, and maybe provided in `QtGui` since then as an alias for backwards compatibility, but the alias was removed at some point.
I'm confused though because `ImaqdxCamera` is in common use and was written long after we moved away from PyQt4, but I don't see `QtGui.QSizePolicy` in PyQt5 5.9 or 5.15. 5.9 is pretty old, so ... how did this ever work? Was `qtutils` providing an alias? If so I don't see it doing so now.
Whatever, as long as `QtWidgets.QSizePolicy` works for everyone, we should be good.
If anyone wants to check if `QtGui.QSizePolicy` or `QtWidgets.QSizePolicy` exist on their systems before I …
> Replace QtGui.QSizePolicy → QtWidgets.QSizePolicy

- docs/source/adding_devices.rst
- docs/source/conf.py
- labscript_devices/NI_DAQmx/models/generate_subclasses.py
Noticed that while the most recent doc build didn't outright fail, a bunch of stub pages were borked. Whatever RTD did most recently, any import of h5_lock just breaks everything.
This mocks `labscript_utils` to prevent h5_lock imports from preventing autodoc importing things on RTD.
> Fix doc builds

- labscript_devices/IMAQdxCamera/blacs_tabs.py
Similar to #92, it looks like the former was an alias provided by
pyqtgraph for backwards compatibility with code written for PyQt4.
pyqtgraph no longer provides this alias.
> Replace QtGui.QApplication → QtWidgets.QApplication

- labscript_devices/AndorSolis/blacs_workers.py
- labscript_devices/FlyCapture2Camera/blacs_workers.py
- labscript_devices/IMAQdxCamera/blacs_workers.py
- labscript_devices/IMAQdxCamera/labscript_devices.py
- labscript_devices/PylonCamera/blacs_workers.py
- labscript_devices/SpinnakerCamera/blacs_workers.py
In the IMAQdx camera class the option exception_on_failed_shot did not catch all the missing shot errors in the lab.  The reason is that for some reason about 0.1% of the time with our gige cameras we would get an error "nivision.core.ImaqDxError: 3220606990: No acquisition in progress."  I don't know why the acquisition would stop before taking all of the images, but sometimes it does.  When this error occurs it pops up a big error box, which can be undesirable.
As a result I added exception_on_failed_shot into the IMAQdx_Camera class so it too can catch errors and respond just as IMAQdxCameraWorker already does.
In addition I added this attribute to all of the cameras that subclass IMAQdx_Camera BUT it does not do anything.  This is so that IMAQdxCameraWorker's subclasses can still …
> Camera error control

- labscript_devices/NovaTechDDS9M.py
This is the corresponding change for labscript-suite/labscript#88
Technically I think this can be as low as 100ns but I'm concerned that some of the tri-state buffer hardware (or similar) that some labs have in front of their NovaTechs might mean this is actually slower. 1us seems like a safe bet while allowing people to command output on other clocklines within a reasonable time frame.
> Added a minimum_clock_high_time attribute the the NovaTechDDS9M labscript device class.

- docs/source/conf.py
- setup.cfg
Docs builds are failing again. Get the error
```
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/labscript-devices/envs/96/lib/python3.7/site-packages/jinja2/__init__.py)
```
It appears that updating the sphinx pin to version 4.4.0 avoids this deprecated import.
Also updates some old intersphinx links.
> Fix docs build

- .github/workflows/release.yml
This helps address labscript-suite/labscript-suite#69.
@chrisjbillington I do have a question about the Build Manylinux Wheels step. It no longer uses the matrix to determine which python versions to wheel for. Given this is a pure, noarch package, can I modify the version string to match the single python version being used in the matrix?
Assuming this all looks good, I'll go ahead and manually update these workflows for all the repos.
> Bring workflow up to date with the sandbox

- docs/source/devices/ni_daqs.rst
- labscript_devices/NI_DAQmx/blacs_tabs.py
- labscript_devices/NI_DAQmx/blacs_workers.py
- labscript_devices/NI_DAQmx/labscript_devices.py
Implement ability to specify an external sample clock timebase signal for analog inputs on an NI-DAQ.
This mitigates issues where the AI clock and the timing pseudoclock can get out of sync with each other, particularly for long shots.
Fixes #80
> Externally clocked analog inputs on NI-DAQmx

- labscript_devices/FunctionRunner/blacs_workers.py
- readthedocs.yaml
- setup.cfg
Updates `runmanager.get_shot_globals` to use `labscript_utils.shot_utils.get_shot_globals`
Partially addresses labscript-suite/runmanager#98
> Get shot globals dependency break

- labscript_devices/PrawnBlaster/blacs_workers.py
The labscript-devices side of [PrawnBlaster PR #25](https://github.com/labscript-suite/PrawnBlaster/pull/25).
Adds a fast binary mode for reprogramming the entire sequence, as well as heuristics for deciding when to use binary mode instead of incremental programming.
Verification testing has been performed, but performance testing is incomplete.
> PrawnBlaster binary programming

- labscript_devices/TekScope/blacs_workers.py
The TekScope device had a bug where it was calling `hdf_file.create_group('/data/traces')` in transition to manual.  This is a problem because if you have two scopes this code fails the second time.  Instead (and like the camera devices) I changed this to `grp = hdf_file.require_group('/data/traces')`.  Trivial.
Also in transition to buffered the code `self.scope.dev.timeout = 1000 * self.scope_params.get('timeout', 5)` appeared while the h5 file was open (which was not needed).  Moved this after closing the h5 file to slightly reduce the time that the file was locked.
> TekScope bug fix

- labscript_devices/SpinnakerCamera/blacs_workers.py
Previously, the buffer count mode for the Spinnaker Camera in blacs_workers.py was set to Auto. This Auto feature has been depreciated by FLIR so I changed it to be manual in the same format as the continuous mode. In the case where bufferCount == 1, I set it to 3 because the Spinnaker SDK mentioned that 3 was the minimum buffer count.
> Changed SpinnakerCamera StreamBufferCountMode
